### PR TITLE
Promise based storing and parsing of metadata.

### PR DESCRIPTION
**Pull request by Borewit**
File based parsing instead of stream based which in in some cases more efficient.

### CODE REVIEW

**Comment by IrosTheBeggar** [comment]
This looks good. I was thinking about switching to that branch of the music-metadata plugin since the old one appears to be dead.  Thanks for taking the time to write this up

I need a few days to run this through some tests on Windows and Linux before merging it.

**Comment by Borewit** [comment]
Good to hear you like it 👍. Nice project you started. 

Take your time, have a good look first. Catching the metadata exception needs some more attention, because it will give problems in he following `then` handlers.

Do you want to be compliant with a specific JavaScript (ECMAScript) version?
I noticed you are using fat arrow notations, a `const` and `let` at some places.

Let me know if you need a hand somewhere.

**Comment by IrosTheBeggar** [comment]
I've been learning javascript as I code this project, so I haven't been consistent with being complaint with any ECMAScript version.  My only rule is that any code must be compatible with Node v6.

I'm currently devoting all my time to working on the [android app](https://github.com/IrosTheBeggar/mstream-android-app), so any help on this project would be awesome.

My next projects are to:

* Finish feature allowing mStream to boot via a JSON config file
* Album Art Lookup
* Scrape Album art from folder
* Test and document the multi-user feature.  Multi-user is supported, it just hasn't been thoroughly tested
* Ability to favorite songs
* Feature to upload songs to library from the client

If you're interested in helping with one of those, let me know.

**Comment by Borewit** [comment]
Impressive start in the JavaScript world.

With android I have no experience, and I am not in the possession of any Android platform. 

I also wrote a little player as part of an unpublished project I worked on:
myaudiowebplayer

I may give you a hand on the album art. I have not seen the album art appearing anywhere, should it be part of a DB album listing? 

What do you mean with: _mStream to boot via a JSON config file_?

With album art lookup you mean, if not embedded in the metadata, and neither found in the folder, then try to grab it from the web?

**Comment by IrosTheBeggar** [comment]
The album art appears in the left hand nav column.  If you click the hamburger button on the top-left, you'll open the side and see the album art and metadata.  I know it's not a great place, but 
I don't have the time to make any big changes to the webapp right now.

capture

**Comment by Borewit** [comment]
Okay, clear.

**Comment by IrosTheBeggar** [comment]
As for 'mStream to boot via a JSON config file', you can currently boot mstream via the command line by pointing to a JSON config file like:

```
mstream /path/to/mstream-sonfig.json
```

The config params are stored in that file.  This method allows for a more complex boot config than adding all the params via the command line.  The biggest advantage is the mutli-user feature can be setup this way

This feature works, it just needs some code to validate the config, and some docs explaining how to setup the config file

**Comment by Borewit** [comment]
Sounds so familiar, all I have to do is document it 😭 
I postpone that forever on my own projects, because technical challenges are so much more tempting to do first.

**Comment by Borewit** [comment]
@IrosTheBeggar: Did you have a chance to look at it?

**Comment by IrosTheBeggar** [comment]
@Borewit 

Sorry, not yet.  I recently picked up a a gig that's taking up all my time.  It pays well and I need to eat at the end of the day.  It should be over in the next 2-3 weeks at which point I plan on getting back to the mStream project

Sorry for the delay

**Comment by IrosTheBeggar** [comment]
Ok my schedule is freeing up now.  I'll get this tested and committed soon

**Comment by IrosTheBeggar** [comment]
I've tested this and merged the changes.  Thanks for contributing to the project!

**Comment by Borewit** [comment]
Hey Paul, are familiar with this project: [webtorrent-desktop](https://github.com/webtorrent/webtorrent-desktop)?

If not, you should give it a try, download it and run it.

**Pull request merged**
