### PR TITLE
Add Volume slider

### PR DESCRIPTION
**Pull request by FoxxMD**
This is pretty much just a functioning hack at the moment to address #42. Basically no styling. But I wanted to initiate this PR so I could ask some questions and clean it up:

1. What is the difference between js `/webapp2` and `/public`?

 I see that public is what is being served but most of the mstream JS files are duplicated across both folders. Why?

2. How should I approach styling?

I see png icons are used someplace while svg in other...and then `icons.png` is just a big ol' file. How 2 use?

3. How can I develop this locally on my mac more easily? 

Following the ubuntu directions fails at `npm link` but I am able to get it working correctly if I skip that and do `node mstream-command-line-boot-wrapper.js ` directly.

### CODE REVIEW

**Comment by IrosTheBeggar** [comment]
```1. What is the difference between js /webapp2 and /public?```

Just ignore webapp2.  I made that a while back in an attempt to refactor some front end changes.  I never finished and at this point I should just remove the folder.

mStream pulls it's frontend in from one folder.  This folder defaults to public but can be changed with the `-i` command.  [I updated the docs to explain how this command works](https://github.com/IrosTheBeggar/mStream/blob/master/docs/cli_arguments.md)

```
2. How should I approach styling?
```

mStream was orginally created using pngs.  Later I switched to svgs which is why you see both.  I would stick to svgs these days.

```
3. How can I develop this locally on my mac more easily?
```

Can you post a dump of what happens when `npm link` fails?

**Comment by FoxxMD** [comment]
output from `npm install`

```
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-No8lEtefnUb9/HE0mueHi7weuVw= integrity checksum failed when using sha1: wanted sha1-No8lEtefnUb9/HE0mueHi7weuVw= but got sha512-m+qzzcn7KUxEmd1gMbchF+Y2eIUbieUaxkWtptyHywrX0rE8QEYqPC07Vuy4Wm32/xE16NcdBctb8S0Xe/5IeQ==. (25587 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-D8Z9fBQYJd6UKC3VNr7GubzoYKs= integrity checksum failed when using sha1: wanted sha1-D8Z9fBQYJd6UKC3VNr7GubzoYKs= but got sha512-4AH6Z5fzNNBcH+6XDMfA/BTt87skxqJlO0lAh3Dker5zThcAxG6mKz+iGu308UKoPPQ8Dcqx/4JhujzltRa+hQ==. (4142 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-iTMSr2myEj3vcfV4iQAWce6yyFM= integrity checksum failed when using sha1: wanted sha1-iTMSr2myEj3vcfV4iQAWce6yyFM= but got sha512-kKvNJn6Mm93gAczWVJg7wH+wGYWNrDHdWvpUmHyEsgCtIwwo3bqPtV4tR5tuPaUhTOo/kvhVwd8XwwOllGYkbg==. (8851 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.

> bcrypt@1.0.2 install /Users/mduncan/Coding/mStream/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

[bcrypt] Success: "/Users/mduncan/Coding/mStream/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is installed via remote

> sqlite3@3.1.9 install /Users/mduncan/Coding/mStream/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Success: "/Users/mduncan/Coding/mStream/node_modules/sqlite3/lib/binding/node-v48-darwin-x64/node_sqlite3.node" is installed via remote
added 400 packages in 11.842s
```
output from `npm link` (with or without sudo)

```
npm ERR! path /Users/mduncan/Coding/mStream/node_modules/.staging/npmlog-aaa9888a
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/mduncan/Coding/mStream/node_modules/.staging/npmlog-aaa9888a' -> '/Users/mduncan/Coding/mStream/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/npmlog'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

> stick to svgs

Can you recommend an editor? Though for the volume slider, since its "animated", I may try to just style with css as closely as possibly instead of messing around with svgs.

**Comment by IrosTheBeggar** [comment]
I usually get my svg's from either:

https://material.io/icons/ - Free
https://thenounproject.com/ - Costs Money

Usually they're good to go from download.  If I need to do any editing I usually just do it in a text editor.

As for the the npm problems, it looks like it might be a Mac specific thing.  I do all my development on Windows/Linux so I won't be much help here.  It looks like it's asking you to rename a file, maybe give that a try?

**Comment by FoxxMD** [comment]
I went with css for the range -- all of the svg examples I found were overly complicated. It's looking pretty decent if I do say so myself 👍

screen shot 2017-08-30 at 9 55 16 am

Can you elaborate on how to use jukebox mode? It looks like I need to make modifications to `remote.html` as well but I can't figure out how to use the remote.

**Comment by IrosTheBeggar** [comment]
Looks good so far.  There should be a volume icon next to the slider to make it clear what it is.  The icon would also make a good quick mute option.

The player is actually do for a re-design.  This might be a good time and place to make that happen.  I'll post a mockup of the design a little later

**Comment by FoxxMD** [comment]
Oh yes a volume icon! I'll get that in soon. I'm happy to help with the redesign too.

**Comment by IrosTheBeggar** [comment]
@FoxxMD 


Here's how I envision the player part of mStream should be redesigned:

capture

You'll notice there are several new button.  From left to right:

* Juke Box Icon - This Button brings up the Jukebox panel.  It currently is in the left nav drawer.  The icon should change colors when jukebox mode is enabled
* Volume Icon - Brings up a vertical volume slider when clicked
* Shuffle Icon
* Repeat Icon
* Overlay Icon.  This button should expand to fill whatever extra space is left.  When clicked it will bring up an overlay with Album Art and Metadata Info.  This feature currently doesn't exist, but I'll add it as the project goes along

All the icons should be 40x40px.  The seekbar on top should be 25px tall.  

I'm going to create a branch to begin work on this. Do you want to take a try at writing the player CSS while I work on the overlay feature?

**Comment by FoxxMD** [comment]
I'll take a whack at it! Should I just make PR on a new branch or do you want to work in the same branch?

**Comment by IrosTheBeggar** [comment]
The same branch is fine

**Comment by IrosTheBeggar** [comment]
@FoxxMD 

I created a new branch called webapp-redesign.  If you're still interested in helping, I can add you as a collaborator so you can push changes to that branch

**Comment by IrosTheBeggar** [comment]
The master branch has a new UI with a volume.  It doesn't have a slide but does do mute/unmute

Feel free to branch it and add a slider

**Comment by FoxxMD** [comment]
Sorry I didn't get much done on this. Been a busy month! I'll take a look at the new branch

**Comment by IrosTheBeggar** [comment]
@FoxxMD 

The new branch has been merged with the master.  Check it out, it's got some significant UI improvements

**Comment by FoxxMD** [comment]
Thanks for all the hard work! <3 mstream

**Pull request closed without merging**
