### PR TITLE
Support range request combined with ffmpeg

### PR DESCRIPTION
**Pull request by Borewit**
In order to be able to seek in the media stream, I believe a proper handling [HTTP range requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests) is required,

This PR is a start of that work towards the range requests.

### Testing
To be able to test the HTTP-range-requests in a controlled environment I have put a simple client together which is using the HTTP-range-requests to download audio information: [mstream-http-range-client](https://github.com/Borewit/mstream-http-range-client)

Related issue: #213 _Transcoding bugs_

### CODE REVIEW

**Comment by Borewit** [comment]
Using the transcode flag:
```js
const transcode = false;
```
one can switch between transcoded and straight link, in [client.js](https://github.com/Borewit/mstream-http-range-client/blob/master/client.js).

The client currently is able to extract metadata-data without transcoding. This reflects the differences as described in issue #213. 

I suggest to look for an existing library supporting the range requests, such as:
* [ ] [express-range](https://www.npmjs.com/package/express-range)
* [ ] Investigate how we can read chunks from ffmpeg. Maybe it is required to cache it's output.

**Comment by IrosTheBeggar** [comment]
Github says there are merge conflicts. I also noticed this included the same code style commit the other PR had.

**Comment by Borewit** [comment]
Conflicts addressed. 

Since I force pushed, please delete old local branch, and pull a fresh one from GitHub.

Don't merge this one into the master as it is not suitable for production.

**Comment by Borewit** [comment]
It was just a beginning...

**Comment by IrosTheBeggar** [comment]
@Borewit for experimental features I like to put commits out early and often.  Some of the more active users find and report bugs and give feedback

I made sure to do a cross platform and cross-browser test first

**Pull request merged**
